services:
  back-end:
    container_name: back-end
    image: node:18-alpine
    ports:
      - '3001:3001'
    restart: always
    working_dir: /app
    volumes:
      - ./src/mock/server:/app
    network_mode: host
    command: ['npx', 'json-server', '--watch', 'db.json', '--port', '3001']

  front-end:
    container_name: front-end
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - back-end
    network_mode: host
    environment:
      - JWT_SECRET=secret123
      - REACT_API_URL=http://host.docker.internal:3001
      - SETTINGS_URL=http://host.docker.internal:3002



